# Generated by Django 4.2.3 on 2023-07-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='país',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='docentes',
            old_name='país',
            new_name='pais',
        ),
    ]
